# schemas/chat_schemas.py
# ══════════════════════════════════════════════════════════════════════
#  Pydantic Schemas — AI Chatbot Request & Response Models
#
#  Schemas in this file:
#    ChatMessageRequest  — body for POST /api/user/chat/{session_id}
#    ChatMessageResponse — one message returned in history
#    ChatHistoryResponse — full conversation history for a session
# ══════════════════════════════════════════════════════════════════════

from pydantic import BaseModel, Field
from typing import Optional, List


# ══════════════════════════════════════════════════════════════════════
#  CHAT MESSAGE REQUEST
#  Used by: POST /api/user/chat/{session_id}
#  The clinician sends a plain text message.
#  The session_id comes from the URL path — not the request body.
# ══════════════════════════════════════════════════════════════════════

class ChatMessageRequest(BaseModel):

    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description='The clinician message to send to the AI assistant'
        # Examples:
        # "What do these diabetes results mean for this patient?"
        # "What lifestyle changes should I recommend?"
        # "Is the CKD result concerning given the patient's age?"
    )


# ══════════════════════════════════════════════════════════════════════
#  CHAT MESSAGE RESPONSE
#  Represents one message in the conversation history.
#  Used inside ChatHistoryResponse.
# ══════════════════════════════════════════════════════════════════════

class ChatMessageResponse(BaseModel):

    id: int
    # Auto-generated database row ID

    role: str
    # 'user'      → sent by the clinician
    # 'assistant' → generated by the Groq LLM

    content: str
    # The actual message text

    created_at: str
    # ISO timestamp of when this message was created


# ══════════════════════════════════════════════════════════════════════
#  CHAT RESPONSE
#  Returned by: POST /api/user/chat/{session_id}
#  Contains the AI assistant reply plus the updated conversation history.
# ══════════════════════════════════════════════════════════════════════

class ChatResponse(BaseModel):

    session_id: int
    # The session this conversation belongs to

    assistant_reply: str
    # The AI-generated response to the clinician's message

    total_messages: int
    # Total number of messages in this session's conversation so far


# ══════════════════════════════════════════════════════════════════════
#  CHAT HISTORY RESPONSE
#  Returned by: GET /api/user/chat/{session_id}
#  Returns the full conversation history for a specific session.
# ══════════════════════════════════════════════════════════════════════

class ChatHistoryResponse(BaseModel):

    session_id: int
    patient_name: str
    # The patient this session belongs to — for context display

    total_messages: int
    # Total number of messages in this conversation

    messages: List[ChatMessageResponse]
    # All messages ordered oldest to newest
    # Alternates between role='user' and role='assistant'
